# Generated by Django 5.2.7 on 2026-05-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MLModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("file_path", models.CharField(blank=True, max_length=500)),
                ("metrics_path", models.CharField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploading", "上传中"),
                            ("training", "正在训练"),
                            ("completed", "训练完成"),
                            ("failed", "训练失败"),
                        ],
                        default="uploading",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("trained_at", models.DateTimeField(blank=True, null=True)),
                ("training_time", models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
