# Generated by Django 6.0.5 on 2026-05-17 12:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dataset", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Model",
            fields=[
                (
                    "model_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_provided_name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("model_file_path", models.CharField(max_length=255)),
                ("evaluation_file_path", models.CharField(blank=True, max_length=255)),
                (
                    "training_status",
                    models.CharField(
                        choices=[
                            ("pending", "待训练"),
                            ("training", "训练中"),
                            ("completed", "已完成"),
                            ("failed", "训练失败"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                ("update_time", models.DateTimeField(auto_now=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dataset.dataset",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "模型",
                "verbose_name_plural": "模型",
                "ordering": ["-create_time"],
            },
        ),
    ]
